import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { useTodos } from "@/hooks/useTodos";
import { Todo } from "@/components/Todo";
import { TodoCreation } from "@/components/TodoCreation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { todos, todosError, todosIsValidating } = useTodos();

  return (
    <>
      <Head>
        <title>Todoアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Todoアプリ</h1>
        <div className={styles.todos}>
          {todosIsValidating && <p>Refreshing...</p>}
          {todosError && <p>Failed to fetch todo lists</p>}
          {!todos || (todos.length === 0 && <p>No data</p>)}
          {todos && todos.map((todo) => <Todo key={todo.id} {...todo} />)}
        </div>
        <TodoCreation />
      </main>
    </>
  );
}
